### ISSUE TITLE
delete separator not working

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#100]
![cannot_delete_separators](https://user-images.githubusercontent.com/17204819/126405267-65475eb7-fe9c-4863-b41f-bce8767a26f5.gif)
[asuite.zip](https://github.com/salvadorbs/Asuite/files/6851640/asuite.zip)

**Comment by salvadorbs** [comment]
I tested in the development version of ASuite and it even crashed. I solved the problem (in this commit 392565e), but I would prefer you to test it too, before closing the issue (if you have time, of course :)).

Last compilation https://github.com/salvadorbs/Asuite/actions/runs/1053173980

**Comment by megabugman** [comment]
confirm, issue is fixed. 
thanks for the nightly build.
