### ISSUE TITLE
alpha app closes with right click option "show classic menu"

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#104]
![image](https://user-images.githubusercontent.com/17204819/126409531-79128f7c-c00b-4851-bd39-329872d0dd9b.png)
![bug](https://user-images.githubusercontent.com/17204819/126409634-6d14bdcb-e527-4a0d-bb39-69d69c02abe0.gif)
the app probably crashes, not checked though.
OK, enough bug huntin for today, I guess :)

**Comment by salvadorbs** [comment]
I should have fixed this some time ago (after the release of alpha1).

>  OK, enough bug huntin for today, I guess :)
Eheh. Thank you very much!

**Comment by megabugman** [comment]
nope issue persists (sort of), it crashed, but atm it works :/
![image](https://user-images.githubusercontent.com/17204819/126558065-7e726701-5fcc-4c5f-9c57-33d2fa1a2496.png)

**Comment by megabugman** [comment]
crashed again, Houston we got a problem here :)
![image](https://user-images.githubusercontent.com/17204819/126559445-f93a2dea-4f19-42c7-9661-b998036ee9a6.png)

**Comment by megabugman** [comment]
haha, gotcha :)
1. show modal about
2. right click
-> reproducible crash (at least for me)
![crash](https://user-images.githubusercontent.com/17204819/126560549-e82cbf86-d7e3-4d04-bf48-473b57300fcc.gif)

**Comment by salvadorbs** [comment]
I tried it on my computer and had no problems. At this point, let's try to increase the logs to understand what happens (so as to also take advantage of the opportunity to improve ASuite logging).

I made a new branch and consequently a pull request, so as to have a build with some more logs in the UpdateClassicMenu function (where the problem seems to be): https://github.com/salvadorbs/Asuite/actions/runs/1057061974

Can you test this build and send me the log file? We hope the stack trace is logged.

**Comment by megabugman** [comment]
so far, the crash did not yet occur but I found another issue:
![new issue](https://user-images.githubusercontent.com/17204819/126696885-7bab75dd-96b1-43b8-9a4d-cd07ebbc887f.gif)

i'll try to repro the crash...

**Comment by megabugman** [comment]
I found something, but this is not the crash issue, this build is more stable so far :)

Heap dump by heaptrc unit of D:\ASuite Debug build - win32\bin\ASuite.exe
108365 memory blocks allocated : 40658989/40807248
108363 memory blocks freed     : 40658869/40807128
2 unfreed memory blocks : 120
True heap size : 1114112 (160 used in System startup)
True free heap : 1113216
Should be : 1113448
Call trace for block $00000000015E1030 size 48
  $0000000100012E4B
  $000000010000F3B0
  $00000001003DDAF6  ENUMERATEFORMATS,  line 4549 of VirtualTrees.pas
  $0000000100406407  GETNATIVECLIPBOARDFORMATS,  line 22191 of VirtualTrees.pas
  $00000001003E0F3B  CREATE,  line 99 of include/intf/win32/vtvdragmanager.inc
  $0000000100411065  CUTTOCLIPBOARD,  line 26684 of VirtualTrees.pas
  $000000010016C374  ACTCUTEXECUTE,  line 209 of Forms/Forms.Main.pas
  $000000010017E4AC
  $00000001001C24D4  EXECUTE,  line 98 of include/containedaction.inc
  $00000001001C435C  EXECUTE,  line 246 of include/customaction.inc
  $000000010017E24B
  $00000001001BD0BD  CLICK,  line 86 of include/menuitem.inc
  $00

Heap dump by heaptrc unit of D:\ASuite Debug build - win32\bin\ASuite.exe
108365 memory blocks allocated : 40658989/40807248
108363 memory blocks freed     : 40658869/40807128
2 unfreed memory blocks : 120
True heap size : 1114112 (160 used in System startup)
True free heap : 1113216
Should be : 1113448
Call trace for block $00000000015E1030 size 48
  $0000000100012E4B
  $000000010000F3B0
  $00000001003DDAF6  ENUMERATEFORMATS,  line 4549 of VirtualTrees.pas
  $0000000100406407  GETNATIVECLIPBOARDFORMATS,  line 22191 of VirtualTrees.pas
  $00000001003E0F3B  CREATE,  line 99 of include/intf/win32/vtvdragmanager.inc
  $0000000100411065  CUTTOCLIPBOARD,  line 26684 of VirtualTrees.pas
  $000000010016C374  ACTCUTEXECUTE,  line 209 of Forms/Forms.Main.pas
  $000000010017E4AC
  $00000001001C24D4  EXECUTE,  line 98 of include/containedaction.inc
  $00000001001C435C  EXECUTE,  line 246 of include/customaction.inc
  $000000010017E24B
  $00000001001BD0BD  CLICK,  line 86 of include/menuitem.inc
  $00


  $00000001001BD94A  DOCLICKED,  line 296 of include/menuitem.  $000000010000FF81
  $000000010028F388  DOWINDOWPROC,  line 2145 of win32/win32callback.inc
  $0000000100290DF0  WINDOWPROC,  line 2775 of win32/win32callback.inc
Call trace for block $0000000007F0E1F0 size 72
  $0000000100012D72
  $000000010000FB7A
  $000000010001080A
  $00000001003E0EDE  CREATE,  line 94 of include/intf/win32/vtvdragmanager.inc
  $0000000100411065  CUTTOCLIPBOARD,  line 26684 of VirtualTrees.pas
  $000000010016C374  ACTCUTEXECUTE,  line 209 of Forms/Forms.Main.pas
  $000000010017E4AC
  $00000001001C24D4  EXECUTE,  line 98 of include/containedaction.inc
  $00000001001C435C  EXECUTE,  line 246 of include/customaction.inc
  $000000010017E24B
  $00000001001BD0BD  CLICK,  line 86 of include/menuitem.inc
  $00000001001BD94A  DOCLICKED,  line 296 of include/menuitem.inc
  $000000010000FF81
  $000000010028F388  DOWINDOWPROC,  line 2145 of win32/win32callback.inc
  $0000000100290DF0  WINDOWPROC,  line 2775 of win32/win3

![image](https://user-images.githubusercontent.com/17204819/126699466-9c658978-e3f0-467a-a3e9-ac180fc21fca.png)

**Comment by megabugman** [comment]
I renamed the themes folder in desperate attempt, now application cannot longer be closed,
somehow fair, I got a warning, nevertheless an app should always manage to close itself :)

heap.trc, log seems to work:

D:\ASuite Debug build - win32\bin\ASuite.exe 
Heap dump by heaptrc unit of D:\ASuite Debug build - win32\bin\ASuite.exe
95592 memory blocks allocated : 38979900/39051192
95582 memory blocks freed     : 38979299/39050568
10 unfreed memory blocks : 601
True heap size : 2457600 (160 used in System startup)
True free heap : 2454592
Should be : 2454896
Call trace for block $00000000064CD190 size 131
  $000000010001AF09
  $0000000100012E4B
  $000000010000AFDB
  $000000010000A0FD
  $000000010003CEB2
  $000000010003E0E0
  $0000000100032D98  SHOWEXCEPTION,  line 1547 of include/application.inc
  $0000000100031E80  HANDLEEXCEPTION,  line 1245 of include/application.inc
  $00000001000324F0  RUNLOOP,  line 1385 of include/application.inc
  $000000010018F16B  APPRUN,  line 54 of include/interfacebase.inc
  $000000010003249A  RUN,  line 1371 of include/application.inc
  $000000010000373C  main,  line 56 of ASuite.lpr
  $00000001000037A6
  $0000000100018CF0
  $0000000100003507
  $00007FFB22467034
Call trace for block $0000000007F90FA0 size 49
  $0000000100012D72
  $0000000100009D93
  $000000010000AFF2
  $000000010000A0FD
  $0000000100032CA9  SHOWEXCEPTION,  line 1535 of include/application.inc
  $0000000100031E80  HANDLEEXCEPTION,  line 1245 of include/application.inc
  $00000001000324F0  RUNLOOP,  line 1385 of include/application.inc
  $000000010018F16B  APPRUN,  line 54 of include/interfacebase.inc
  $000000010003249A  RUN,  line 1371 of include/application.inc
  $000000010000373C  main,  line 56 of ASuite.lpr
  $00000001000037A6
  $0000000100018CF0
  $0000000100003507
  $00007FFB22467034
  $00007FFB22A62651
  $00007FFB1DB4A919
Call trace for block $000000000C672E40 size 40
  $0000000100012E6B
  $00000001000191C6
  $0000000100019675
  $00007FFB22AB217F
  $00007FFB22A61454
  $00007FFB22A611A5
  $00007FFB20304ED9
  $000000010001903B
  $000000010004998A
  $0000000100012668
  $0000000100012702
  $000000010001209E
  $0000000100587316  SAVEDATA,  line 202 of Library/Database.Manager.pas
  $0000000100165D3A  SAVELIST,  line 190 of Library/Kernel.Instance.pas
  $000000010016D39B  MISAVELISTCLICK,  line 459 of Forms/Forms.Main.pas
  $00000001001BD095  CLICK,  line 83 of include/menuitem.inc
Call trace for block $00000000064CCAB0 size 128
  $000000010001AD8B
  $0000000100012E4B
  $0000000100018F5A
  $0000000100019013
  $000000010004998A
  $0000000100012668
  $0000000100012702
  $000000010001209E
  $0000000100587316  SAVEDATA,  line 202 of Library/Database.Manager.pas
  $0000000100165D3A  SAVELIST,  line 190 of Library/Kernel.Instance.pas
  $000000010016D39B  MISAVELISTCLICK,  line 459 of Forms/Forms.Main.pas
  $00000001001BD095  CLICK,  line 83 of include/menuitem.inc
  $00000001001BD94A  DOCLICKED,  line 296 of include/menuitem.inc
  $000000010000FF81
  $000000010028F388  DOWINDOWPROC,  line 2145 of win32/win32callback.inc
  $0000000100290DF0  WINDOWPROC,  line 2775 of win32/win32callback.inc
Call trace for block $000000000C672840 size 24
  $0000000100012D72
  $

![corrupt](https://user-images.githubusercontent.com/17204819/126701580-4d9b3ba4-0e4e-46fa-91f5-fcfab3e36edf.gif)

->granted that's not fair!

**Comment by megabugman** [comment]
OK, i give up. you can't force an knock out :)

-> could not reproduce the right mouse button crash so far with 2.1.0.1341

**Comment by megabugman** [comment]
I guess the issue is gone, I'll re-open or create a new ticket when crash re-occures.

**Comment by salvadorbs** [comment]
In ASuite.log there is no exception?

**Comment by salvadorbs** [comment]
Found. If there is a separator in the list, ASuite will fail when you try to open the classicmenu. In the new build, the problem is handled, but not visually reported to the user (there is just something in the log). 

Before solving it, I want to try to improve the logs and add an error message.

I reopen the issue.

**Comment by megabugman** [comment]
no more crashes in latest build 2.1.0.1539
