### ISSUE TITLE
 Updated FPCUp (fpc & lazarus gitlab support) Build push events (debug mode) #277

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#116]
win 10 won't start
![image](https://user-images.githubusercontent.com/17204819/128714718-7376e4b7-a0a5-434f-920b-2b971c68afeb.png)

**Comment by salvadorbs** [comment]
Fixed. See https://github.com/salvadorbs/Asuite/actions/runs/1113280179
