### ISSUE TITLE
Search Table width is not saved 

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#117]
after reboot, standard width is shown
![image](https://user-images.githubusercontent.com/17204819/128763773-9bc6cb41-f4ed-4760-96c3-da38a9eceb51.png)

**Comment by megabugman** [comment]
I assume double click should keep a certain width 
![doubleclick](https://user-images.githubusercontent.com/17204819/128782594-fdae5f21-c078-43db-8873-84e94820d30a.gif)
minimize the app, restore to note the issue I see

**Comment by salvadorbs** [comment]
For search width, it shouldn't be a problem to save the data in the settings.json file. For autosize columns, I have to find a solution that is not based solely on default values (as I did for hotkeys).

**Comment by salvadorbs** [comment]
Fixed. Search widths are saved in settings.json.

Furthermore, the resize now also takes into account the header caption.
