### ISSUE TITLE
Edit control size changes when hotkey set

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#119]
I noticed the Edit1,2,3 width changes when a hotkey is set:

![image](https://user-images.githubusercontent.com/17204819/128783595-a38cc97f-18ae-4277-80db-00952fadd7be.png)

this minor issue is a bit distracting

**Comment by salvadorbs** [comment]
Fixed. New icons:
![EEOFjN9rqD](https://user-images.githubusercontent.com/3731721/129567781-f7489e55-e8f0-478c-9a73-89cab0be59aa.gif)
