### ISSUE TITLE
minor issue: repetition

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#120]
I believe you can omit some/all program name references:
![image](https://user-images.githubusercontent.com/17204819/128783919-2946ef93-3844-440b-a962-c986a616e60e.png)

**Comment by salvadorbs** [comment]
In fact, there are too many repetitions too.

**Comment by salvadorbs** [comment]
Some changes:
![immagine](https://user-images.githubusercontent.com/3731721/129442272-c97f1771-0360-4bcd-b01a-368b4bc1f9b7.png)

**Comment by megabugman** [comment]
fixed
