### ISSUE TITLE
localization issue only partially fixed

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#122]
should be "Properties":
![image](https://user-images.githubusercontent.com/17204819/128784793-9a4f7ebc-13c0-4127-b066-f360029dccc6.png)

maybe you want to show the item name before "Properties" like in windows explorer?
![image](https://user-images.githubusercontent.com/17204819/128784874-b9c34e3c-7ea9-499b-91b8-28a88e2a1408.png)

OK now:
![image](https://user-images.githubusercontent.com/17204819/128784693-be197fb0-a0f0-453f-9b73-cfd6452e0ada.png)

**Comment by salvadorbs** [comment]
Yes, it just slipped out. Thank you! 😅
