### ISSUE TITLE
critical issue: EConvertError: invalid argument

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#124]
I scanned for my user folder, now I get an error:
![image](https://user-images.githubusercontent.com/17204819/128785250-1f99dc6b-168e-4e91-a4e3-5959c8624c98.png)

-> ASuite cannot be exited any more! I guess the database is corrupted
Luckily I have a backup :)

**Comment by salvadorbs** [comment]
Found. In the user \ appdata \ folder there are some executable files with no data inside (0 bytes, see AppleInc.Defaults.exe).

This causes issue (no data -> no hash -> error) for the icon cache hash function. It should now avoid retrieving the hash for files with 0 bytes.
