### ISSUE TITLE
enhance error message

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#128]
the picture was deleted, hence the message is correct:
![image](https://user-images.githubusercontent.com/17204819/128789161-70e3f9ea-b2a6-42ec-a2b0-d806be31a203.png)
but could be enhanced, by adding the reason "... item not found".

**Comment by salvadorbs** [comment]
Fix in commit c8e44f4ab1a9d69cc2bef8a9abdc2fa3ee7bf02c. Please test it.
