### ISSUE TITLE
Load treeview background other than PNG and BMP files

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#129]
![error](https://user-images.githubusercontent.com/17204819/128789561-e2b08944-a8b8-42c1-aeef-1d1cada4449b.gif)

**Comment by salvadorbs** [comment]
The problem is not caused by the disabled scheduler, but by the fact that you have set an .exe file as the background of the treeview. 

The only supported formats are png and bmp files. However, if the user enters a format other than these two, now ASuite does not try to load them.

Thank you!
