### ISSUE TITLE
Hotkey not working as expected

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#133]
![image](https://user-images.githubusercontent.com/17204819/130516641-bad14f0c-f283-4dc0-9744-448403549a44.png)
I have set this hotkey.

When another app is active I need to press Ctrl+F12 twice in order to show ASuite window.

**Comment by megabugman** [comment]
fixed in latest build.

**Comment by megabugman** [comment]
this issue is not fixed (properly).

to reproduce set a hotkey to show window when hotkey is pressed, then partially cover ASuite with another window, now press the hotkey. 
-> ASuite is minimized. 
-> this is not the correct behavior. instead, it should become the topmost window.

**Comment by salvadorbs** [comment]
Fixed in 708d721de6f8670fec010e98d3765e330b40f02f. Please test it. Thank you!
