### ISSUE TITLE
Option to execute as admin

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#134]
some applications do not start, they crash immediately.
These applications work if "run as admin".
Please add an option in properties to run application always as admin.
![image](https://user-images.githubusercontent.com/17204819/130959693-4947cbaa-523c-4619-b09a-2265b382e8cf.png)

**Comment by megabugman** [comment]
Sure. How can I send you a private message/file?

**Comment by megabugman** [comment]
I did more tests in 2.1.0.1588, apps run as expected, in 2.1.0.1591 not!
From what I can tell the culprit seems to be
Installer: Nullsoft Scriptable Install System

**Comment by salvadorbs** [comment]
@megabugman Another test with commit 71442117192800a3775655174ae61fd605d28ee3 (https://github.com/salvadorbs/Asuite/actions/runs/1405098581). Please test it. I hope it's the right time. Thank you very much. 😄

**Comment by megabugman** [comment]
OK, thanks it works now. I'll open a new issue regarding the icon display problem.

**Comment by megabugman** [comment]
sorry, it worked yesterday. today not, I'm using 2.1.0.1600. I hope you can reproduce the issue:
![crash](https://user-images.githubusercontent.com/17204819/140031701-43ee5246-ab20-4efd-aca6-7eb48dc2fd34.gif)

**Comment by salvadorbs** [comment]
> Why not use an apimonitor and spy on other program launchers? You may want to add some sort of logging in case a thread has existed immediately. My 2 cents.

It's a great idea, but I'm having trouble detecting which api are used in other launchers (eg pstart).

**Comment by megabugman** [comment]
Which function are you using? Try
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew
![image](https://user-images.githubusercontent.com/17204819/140593676-40e65e2e-e7f2-4cd8-a499-7ff646138c91.png)

**Comment by salvadorbs** [comment]
Great, I had assumed that PStart used the ShellExecuteW API. ASuite uses CreateProcessW to have shared code between Windows and Linux.

With this PR https://github.com/salvadorbs/Asuite/pull/146, I decided to go back to having two different codes. In Windows I will use ShellExecuteEx, while in Linux CreateProcess. This PR is not yet complete, as there is still no support for custom environment variables in Windows. But I believe you can already start testing.

**Comment by megabugman** [comment]
All applications start so far in 2.1.0.1611. I keep testing...

**Comment by megabugman** [comment]
Works as expected also 2.1.0.1613, closing report
