### ISSUE TITLE
Seperators should not be auto-sorted

### ISSUE THREAD

**Issue by actually-reb** [salvadorbs/Asuite#135]
Right now, the auto-sort function doesn't work well with separators. Because items and separators are treated exactly the same way, so they all get jumbled together when they're sorted. Ideally, separators would stay where they are, and items would be sorted under each separator individually.

**Comment by megabugman** [comment]
I agree

**Comment by Laynee** [comment]
> separators would stay where they are, and items would be sorted under each separator

Good idea!
