### ISSUE TITLE
Incorrect Path in Settings

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#150]
Press Button to open custom icon path:
![wrong path](https://user-images.githubusercontent.com/17204819/141136717-4aa839f0-8f1b-4cd7-bdea-4f464e6f1399.gif)
-> in my case windows explorer should open "D:\ASuite Debug build - win32\bin\icons" not "D:\ASuite Debug build - win32\bin"

**Comment by salvadorbs** [comment]
Fixed in commit 343ff72a4ec929813740d6ea9fe2ff89c422c269
