### ISSUE TITLE
[2.1.0.1605] Don't show a messageBox after canceling the RunAs Dialog

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#151]
the command was canceled, hence it makes no sense to moan the missing user name
![cancel_bug](https://user-images.githubusercontent.com/17204819/141614625-623b3d90-bca7-4fa2-a8b4-7a98e3af7cde.gif)
.

**Comment by salvadorbs** [comment]
Fix in commit 27457bc4dd05bb039826b9304da06576e40d8945 (in PR #146 ). Thanks.
