### ISSUE TITLE
Keyboard Shortcut to Access Asuite Floating Menu

### ISSUE THREAD

**Issue by mikjsmith** [salvadorbs/Asuite#153]
**Is your feature request related to a problem? Please describe.**
Currently the Asuite program window or graphical menu can be accessed via an assigned keyboard shortcut.

**Describe the solution you'd like**
 I would like to be able to access the floating menu (ie. the same as left clicking the tray icon) via a keyboard shortcut

**Comment by salvadorbs** [comment]
By floating menu, do you mean the classic menu? If yes, it was already added some time ago in unstable versions:

![image](https://user-images.githubusercontent.com/3731721/143067742-ec0a3082-da3d-4d39-8ff4-251e1287ccfd.png)

**Comment by mikjsmith** [comment]
Yes, thats it! Great!!

Does it support the Win key in the shortcut as well, as that doesnt appear a valid option at the moment?

**Comment by salvadorbs** [comment]
Yep: 

![image](https://user-images.githubusercontent.com/3731721/143074159-347dee9f-1c8d-47c3-be6b-40ea4b0e2205.png)

I will close this issue.
