### ISSUE TITLE
How to locale, POT/PO, MO or LNG files?

### ISSUE THREAD

**Issue by c-sanchez** [salvadorbs/Asuite#154]
**Hello, I would like to translate ASuite v2 into Spanish, however I find this a bit confusing.**

The ASuite v2 installer / binaries include the locale folder, and a translation file *.lng in Italian.
However, in the source code you can find the POT files in English for translation.

I think that using POT files is one of the best options, but I don't understand why the binary uses *.LNG files, I don't know with which program to translate this file, I don't know Italian either heh.

With Poedit I only find that I translate PO files and then they are saved as MO (compiled), I can't find anything about exporting to LNG.

**Comment by salvadorbs** [comment]
ASuite 2.0 uses library DKLang for localization. With the move to Lazarus / FPC, I preferred to use the more standard gettext, already available out of the box in Lazarus. So you can very well start from the .pot file (using poedit or another po editor) in this repo to create the Spanish translation.

In the future I hope to find an online platform to facilitate the creation of translations.
