### ISSUE TITLE
Classic Menu Re-opens After Clicking App

### ISSUE THREAD

**Issue by AntumDeluge** [salvadorbs/Asuite#155]
ASuite version: 2.1 Alpha 1 (64-bit)
OS: Windows 10 64-bit

I'm not sure if this has been fixed since 2.1 Alpha 1 was released.

Issue: After executing an app from the classic menu, classic menu closes then immediately re-opens. App does launch fine, but classic menu remains visible until clicking somewhere else on screen.

Steps to reproduce:
1. Click tray icon to open classic menu.
2. Select app to launch & click it.
3. Classic menu will close, then will immediately display again in the same position.
4. Clicking on the taskbar will close the re-opened classic menu.

**Edit:** I noticed this actually occurs even when an app is not selected.

Steps to reproduce:
1. Click tray icon to open classic menu.
2. Click anywhere on taskbar or other part of the screen to close classic menu. It will close & immediately re-open.
3. Classic menu will remain on screen until an app or other entry is clicked.

**Comment by AntumDeluge** [comment]
Are there pre-built binaries available? The links from that action appear to be expired.

**Comment by salvadorbs** [comment]
Ops... in any case I have released a new alpha: https://github.com/salvadorbs/Asuite/releases/tag/v2.1.0-alpha2

Thanks!

**Comment by AntumDeluge** [comment]
Oh, thanks. Just when I figured out how to manually run actions & rebuild the packages. 🙂

Tested in v2.1 Alpha 2. Issue is fixed. Thank you.
