### ISSUE TITLE
Bug: Custom Tray Icon doesn't Persist across Application Restarts

### ISSUE THREAD

**Issue by visusys** [salvadorbs/Asuite#161]
I've configured a custom tray Icon for Asuite, but when the application is restarted it reverts to the old rocket icon. I have to manually reset the icon. It would be great if this problem was fixed! I'm on 2.1 alpha 2.

Thanks,
Jay

**Comment by salvadorbs** [comment]
Hello, 

fixed in https://github.com/salvadorbs/Asuite/actions/runs/2476018501

Please check and thank you!
