### ISSUE TITLE
Icons, custom or default, disappear after exiting Asuite.

### ISSUE THREAD

**Issue by saturdayxiii** [salvadorbs/Asuite#163]
![no icons](https://i.imgur.com/2jnSWMa.png)

Apparently [someone had the problem back in 2020 and fixed it](https://www.portablefreeware.com/?id=692), but they didn't know how exactly they fixed it.

**Comment by salvadorbs** [comment]
Seeing your screen, I assume you are using ASuite 2.0. This issue should be fixed in recent development releases.
