### ISSUE TITLE
Theme ini doesn't change list or search text color.

### ISSUE THREAD

**Issue by saturdayxiii** [salvadorbs/Asuite#165]
![img](https://i.imgur.com/zIzn8IF.png)

Unless I'm misunderstanding something.  I replaced every  instance of #000000 in the theme.ini for #ffffff, yet the search text and the text listing programs remains black.

**Comment by salvadorbs** [comment]
Fixed in last [asuite build](https://github.com/salvadorbs/Asuite/actions/runs/2852043329). Please test it. Thanks

**Comment by saturdayxiii** [comment]
Perfect!  Thank you!

**Comment by saturdayxiii** [comment]
[dark.zip](https://github.com/salvadorbs/Asuite/files/9332031/dark.zip)
Here's the files for a simple dark theme to match Windows 10's built in theme, if anybody wants them.

**Comment by salvadorbs** [comment]
Can I add your theme in asuite repo (and packages)?

**Comment by saturdayxiii** [comment]
Yes, for sure.
