### ISSUE TITLE
Have the search box in focus, ready for typing when graphic menu is brought up

### ISSUE THREAD

**Issue by saturdayxiii** [salvadorbs/Asuite#166]
Extremely minor nitpick, but I have a pet peeve about clicking the icon to bring up the graphical menu, then having to click the search bar before I can begin typing.  I'd love it if I could just open the graphic menu and begin typing an app name, rather than having to pinpoint and click the search bar first.

**Comment by salvadorbs** [comment]
Sorry for late. Fixed. You can test it with [last build](https://github.com/salvadorbs/Asuite/actions/runs/2912153800).

**Comment by saturdayxiii** [comment]
You are amazing!
