### ISSUE TITLE
Heat dump by heaptrc unit error

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#174]
I believe this is due to the shortcut issue:
![20220916150039](https://user-images.githubusercontent.com/17204819/190644742-9a7f8360-3f33-4bf0-83a7-2d705b2406f9.PNG)

I guess this leads to:
![20220916143120](https://user-images.githubusercontent.com/17204819/190644855-c9650a9a-5fa6-4be1-9ae3-0b33f6ee45da.PNG)

**Comment by salvadorbs** [comment]
Can you send me the heap.trc file?

**Comment by megabugman** [comment]
![20220920003859](https://user-images.githubusercontent.com/17204819/191131912-8d04f89e-4b73-4c12-bb39-000496e1b92e.PNG)

**Comment by salvadorbs** [comment]
There is no leak and therefore that window should not appear. I made a quick change, could you try it? https://github.com/salvadorbs/Asuite/actions/runs/3129273695

**Comment by megabugman** [comment]
Heat dump by heaptrc does no longer appear, though I get this when starting:
![nightly](https://user-images.githubusercontent.com/17204819/193434351-91b8844f-e60a-402d-b2b2-11676be2a528.png)

**Comment by salvadorbs** [comment]
Console output should no longer appear. https://github.com/salvadorbs/Asuite/actions/runs/3190131585

**Comment by megabugman** [comment]
yes, you are right, works now.
