### ISSUE TITLE
aSuite - v2.1 Alpha 2 - Error when closing

### ISSUE THREAD

**Issue by PeterPan8** [salvadorbs/Asuite#179]
Hi, Just trying out v2.1-Alpha 2 and upon shutting down the software, I received the following error:
![Error - v2 1-Alpha 2 - June 5 2023](https://github.com/salvadorbs/Asuite/assets/33498049/ed035daa-0700-446c-8cc1-317f24da140c)

**Comment by salvadorbs** [comment]
It's a harmless message. I should have removed them some time ago, if I'm not mistaken.
