### ISSUE TITLE
Icons not refreshing

### ISSUE THREAD

**Issue by PeterPan8** [salvadorbs/Asuite#185]
I went back to version 2.0 (64 bit) and all icons remains the same, even if I change them.  I did many restart, and icons won't change to new icon values.  My main Photo app is FastStone Viewer, and all categories and sub-categories keep the FastStone icon. 

![WrongIcons](https://github.com/salvadorbs/Asuite/assets/33498049/95f72fa1-58e7-4b46-97b2-33766fa2c650)

**Comment by salvadorbs** [comment]
ASuite 2.0 is too old a version to support. In any case, I would suggest you try disabling the cache. Closing
