### ISSUE TITLE
Support install *.paf files and PortableApps Updater

### ISSUE THREAD

**Issue by salvadorbs** [salvadorbs/Asuite#28]
Support *.paf (PortableApps Format) files and PortableApps Updater

**Comment by vectorspin** [comment]
I don't know if this is useful but for reference, there's a freeware updater put out by nozavi that updates PFW but is sadly not open source:

Home: http://apps.nozavi.com/portable-software-updater-overview
PFW entry: http://www.portablefreeware.com/index.php?id=1975

**Comment by vatterspun** [comment]
The workaround that I do for this is just to open the PortableApps program, run the updater, and then close.  There are a host of reasons I choose Asuite over PortableApp's, not the least of which is the ability to have launch arguments.

**Comment by salvadorbs** [comment]
For now, I don't know. I haven't much time to recreate PAF's updater (or extract only updater from PAF Launcher, assuming Haller to permit it). But.

In the last year I found <a href="https://github.com/lukesampson/scoop">Scoop Project</a>, a command line installer and I'm working to use it as backend for a future app package management (or appstore?).
