### ISSUE TITLE
does not run under WinPE

### ISSUE THREAD

**Issue by steve6375** [salvadorbs/Asuite#33]
v 1.5.2 ran under WinPE Win7 32-bit (e.g, from a Win7 32-bit SP1 Install environment), however this version does not run at all.
![captureasuite2_winpe_error](https://cloud.githubusercontent.com/assets/1469350/6998093/10ab0b18-dbcd-11e4-8673-13ded9a56d5d.JPG)
![captureasuite2_winpe_error2](https://cloud.githubusercontent.com/assets/1469350/6998095/12d48978-dbcd-11e4-8ff8-e314fa52651d.JPG)

Is there some new dependency?

**Comment by salvadorbs** [comment]
ASuite 1.5.2 is not supported anymore. You can try ASuite 2.0Beta.
