### ISSUE TITLE
Error on launch Win 7 : EListError error raised, with message: Item not found

### ISSUE THREAD

**Issue by xb31** [salvadorbs/Asuite#34]
After installation with asuite_setup.exe on windows 7 64bits,
followed by 2nd error alert : 'Couldn't find file C:\Program File\ASuite\themes\Default\theme.ini,
followed by 3d error: 'Item not found',
after that, application window open, but click on asuite icon in windows bar open a gray empty window.

**Comment by salvadorbs** [comment]
Thanks for your bug report. Setup doesn't make a folder called themes and so it doesn't put Default theme in this folder.

I just fixed in commit e45936c, but if you want fix your ASuite installation you must create folder "themes" and move folder "Default" in it.
