### ISSUE TITLE
Scan Folder tool bugs

### ISSUE THREAD

**Issue by salvadorbs** [salvadorbs/Asuite#35]
From PortableFreeware.com ASuite topic. http://www.portablefreeware.com/forums/viewtopic.php?f=4&t=196
> I've been having problems with the directory scan tool on both Win7x64 and x86.

> I'll go ahead and post the bug here but please let me know if it belongs elsewhere:

> Setup: Win7x64

> 1. Download 7z version of the 2.0 beta (asuite_x64.7z)
> 2. Scan a directory for executable files and wait for it to finish
> 3. Explore those directories and then try to move the folder

> Defect: get two error msgs "Canvas does not allow" and "Out of system resources". Had to end-task the Asuite.exe program.

> Attempted workaround: I tried the 32 bit version but got an error "You haven't select any folder!" after checking a folder with lots of applications. Edit: tested a Win7x86 machine and got the same error: http://i.imgur.com/fhAVFTf.png

**Comment by vectorspin** [comment]
Hey I'm still a little new to Github ... how do I test the nightly (or whatever) to verify that this works?  I grabbed the asuite-master zip but it doesn't resemble the original program.

**Comment by salvadorbs** [comment]
Hi. I haven't a build machine to make nightly (or similar build). So I build a x64bit version from git, so you can use it. You can download it from https://www.dropbox.com/s/ipb9jd7cazlpkz3/asuite_x64.7z?dl=0

**Comment by vectorspin** [comment]
Actually could you get me the 32-bit nighty as well?  I'd like to re-run that test.

**Comment by salvadorbs** [comment]
No problem. :wink:  https://www.dropbox.com/s/f84e7ngke2ewtqe/asuite.7z?dl=0
