### ISSUE TITLE
Feature request: search-as-you-type [low]

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#39]
Current status: In the main window Search tab, you must type text followed by pressing enter to get information.  

Feature request: search results should appear instantly based on keystrokes.  More keystrokes would refine search results while deleting characters would expand the search.

Goal: usability, speed

**Comment by salvadorbs** [comment]
Simple to do. And I can add an option to select this mode (search-as-you-type) or classic (text and search).
