### ISSUE TITLE
Feature request: scrolling issue [low]

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#40]
Current setting: In a long list of programs, the tops and bottoms of the list are cut off with small arrows: http://i.imgur.com/2XXTBMy.png ... these can only be cycled through one item at a time by clicking repeatedly.  For long lists, this can be problematic and time-consuming.

Feature requests (one or both of the following):

* Mouse scroll wheel moves the list up and down accordingly

* Holding down the mouse button on the arrows (either at the top or bottom) should continue to move through the list.  Currently you have to click multiple times to move the list up or down.

Goal: usability, handling long lists of programs / entries

**Comment by salvadorbs** [comment]
> Mouse scroll wheel moves the list up and down accordingly
It isn't possible without make a new component to mimic a context menu. In fact, context menu are Windows exclusive. And win32 api doesn't support mouse wheel in its context menu.

> Holding down the mouse button on the arrows (either at the top or bottom) should continue to move through the list.  Currently you have to click multiple times to move the list up or down.
On my pc, this works (holding down on the arrows) in ASuite.

**Comment by vatterspun** [comment]
Yeah the holding down item works fine -- I don't know what I missed.  The holding-the-arrow-down to scroll feature should be enough over the scroll wheel.   Please close this issue.

**Comment by salvadorbs** [comment]
Ok. I'll close it.
