### ISSUE TITLE
Feature request: multiple instances of Asuite

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#41]
Current behavior: the program will not allow running more than one copy at a time from two different Asuite folders.

Feature request: ability to create two Asuite folders (or duplicate an existing folder) and have them run concurrently with separate settings.  Ideally these would have changable icon colors to avoid confusion between them.  I'm happy to mock something up if this doesn't make sense.

Goal: flexibility, ability to have different program list views based on need (I have different menus for different tasks)

Possible drawbacks: may cause confusion for some users who accidentally create a second copy or extract Asuite to separate places.  As such this may not be the default setting.

**Comment by salvadorbs** [comment]
Now SingleInstance check window classname and ASuite path (example "c:\path\to\asuite.exe"). In this way, you can execute more than one copy at time from different ASuite folders (but still only one from same folder).

> Possible drawbacks: may cause confusion for some users who accidentally create a second copy or extract Asuite to separate places. As such this may not be the default setting.

Yes, but user can use a custom trayicon to avoid confusion between them. Maybe it's better change trayicon from First Run Wizard (#36), too.

**Comment by vatterspun** [comment]
Hey I just came back to this - how do I test this?  Is this in the nightly?

**Comment by vatterspun** [comment]
Hey just checking back about this: can you give me some idea of how to execute on this?  Maybe a step-by-step?  I am currently running Pstart alongside Asuite for this reason and would like to just stop using Pstart entirely.  Thanks!
