### ISSUE TITLE
Minor UI issue: resizing directory column

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#42]
I was doing a video presentation for Splat and I realized that I really didn't want folks to see the Full Path column so...

Setup Win7x64

1. I minimized the path block. 
2. Clicked on another profile

Defect: Path block no longer minimized

Here's an animated GIF to show my sequence:

https://drive.google.com/file/d/0B9wIWlQojIFwTUZLR25abVNsLWc/view?usp=sharing 

[Please let me know if the animated GIF makes this easier to understand.  I went to some effort to make it so I'm hoping that it can become something for other bug reports I submit to devs.  If there's a better way to do this (e.g. actual video) that works too.]

**Comment by salvadorbs** [comment]
Wrong project?

**Comment by vatterspun** [comment]
That's a way to put it.  Also might be "long weekend".

Sigh.

**Comment by salvadorbs** [comment]
No problem. :smile:
