### ISSUE TITLE
Asuite 2.0beta doesn't recognize Win key

### ISSUE THREAD

**Issue by yangguilong** [salvadorbs/Asuite#43]
I installed Asuite 2.0beta, and like the new options UI very much as it is more intuitive. I planned to switch to this version, but a bug stopped me:  in the hotkey box, it can't recognize Win key. 

When I press `Win+\`, it recognize as `Alt+\`. When I press `Win+Ctrl+Alt+F9`, it recognize as `Ctrl+Alt+F9`.

This is annoying.

**Comment by salvadorbs** [comment]
I removed it in ASuite 2.0. Windows key is reserved for use by the operating system and not by other software ([source](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309%28v=vs.85%29.aspx)).

**Comment by vatterspun** [comment]
Few notes here:

1. Whatever Microsoft's policy, almost every freeware program I've tested with available hotkeys uses or makes available use of the Windows key as part of key combos.  

2. I've got quite a few Windows shortcuts on my system and *not* having access to the can be very limiting, especially for shortcuts you want to execute with one hand (don't have to take your hand off the mouse to use).

That said, Asuite is important enough to my setup that I'd move other hotkeys around it, but new users may be annoyed by this.

**Comment by vatterspun** [comment]
Thanks for reconsidering.

**Comment by yangguilong** [comment]
Glad you're reconsidering this.
:+1:

**Comment by BGMcoder** [comment]
I'll never use this unless I have the choice for Winkey!  I've stayed with 1.52 just for that reason.  I love using the win key for my own purposes.  It's so handy right there in the corner.  I set win+z to open ASuite.  And I use ASuite instead of the start menu to launch programs on my PC.

**Comment by salvadorbs** [comment]
A little surprise-preview:
![immagine](https://user-images.githubusercontent.com/3731721/81503095-0e653780-92e2-11ea-889a-e309530179a0.png)

**Comment by salvadorbs** [comment]
Done.
