### ISSUE TITLE
ASuite crash when use with PHPStorm

### ISSUE THREAD

**Issue by UksusoFF** [salvadorbs/Asuite#45]
Most of times when PHPStorm running ASuite has crashed.

PHPStorm version: 9.0.2
ASuite version: 2.0.0.1422

**Comment by salvadorbs** [comment]
Very strange bug. Anyway do you use some particular PHPStorm's plugins?

**Comment by UksusoFF** [comment]
No, only built-in plugins.

**Comment by UksusoFF** [comment]
Maybe something logs will helpful?
