### ISSUE TITLE
No win key in hotkey possibilities

### ISSUE THREAD

**Issue by BGMcoder** [salvadorbs/Asuite#46]
I have been using Asuite 1.5.2 for ages on my workstation.  I thought I'd give asuite  2.0 x64 a try, but the first thing I notice is that it won't let me assign the win key.  When I push it, it enters it as the alt key instead.

Is there any hope to get the winkey funcitonality?

**Comment by vatterspun** [comment]
Yeah this has come up before: #43

**Comment by BGMcoder** [comment]
Well, I'm going to keep using 1.5.2 until then because I don't want to change the way I am doing things right now.  But I appreciate your work and your kindness for sharing.

**Comment by BGMcoder** [comment]
Ah, right - sorry, I made another entry on the same item...  I still want win key.  It was in 1.52 and I love it (and am still using that version, even now) - it's not nice to update such a wonderful program and remove functionality that people have grown accustomed to using [is crying].

**Comment by salvadorbs** [comment]
Closing this issue because duplicated
