### ISSUE TITLE
Asuite export and import gives incorrect paths for $drive

### ISSUE THREAD

**Issue by BGMcoder** [salvadorbs/Asuite#47]
First I opened asuite 1.5.2 and exported the list.
Then I opened aswuite 2.0 x64 and imported the list.
Anything in the list that had $drive in it was in red and the paths were not resolvable.
So I deleted everything in the list.
And went to the exported list and ran find/replace to turn $drive into c:
Then I imported this list and everything worked perfectly.

I'm just making this report so you know.

**Comment by salvadorbs** [comment]
Sorry for late ( ^^" ), but it works now.
