### ISSUE TITLE
Hotkey to display classic menu

### ISSUE THREAD

**Issue by BGMcoder** [salvadorbs/Asuite#49]
In 1.5.2 there was a hotkey to display the classic menu, but this is missing in version 2.
Can we have it back, please? (pretty please)

**Comment by teamayu** [comment]
This needs to be added back. Without it, it's useless, so I'm reverting back to the previous version.

**Comment by salvadorbs** [comment]
Of course, this option will return in ASuite soon. :)

**Comment by salvadorbs** [comment]
Done in commit 6816665

**Comment by teamayu** [comment]
Thank you.
