### ISSUE TITLE
[2.0 beta] Directory scan failure

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#50]
I don't know if this is related to #35 but when I try to scan a folder for additions, I'm running into an error.

Setup: Win7x86

Steps:

1. Download 7z distro, decompress and launch
2. From the menu, select File - Scan for Files
3. Select File Types - .LNK and click **Delete** 
3. Check a folder

![2017-01-25 16_28_14-scan folder](https://cloud.githubusercontent.com/assets/1289134/22312085/18964b50-e31c-11e6-90e6-39a702c08eda.png)

4. Click Scan

Defect: error screen:

![2017-01-25 16_28_12-asuite](https://cloud.githubusercontent.com/assets/1289134/22312014/c7a0ccc0-e31b-11e6-8bf4-b60fcd62e712.png)

**Comment by salvadorbs** [comment]
Yesterday I rewritten ScanFolder's core source, and updated support for 3p components (see shell tree explorer). Now it is working again and faster than before.

Unfortunately, we lost flat structure checkbox, but I can't see how he's a great loss.
