### ISSUE TITLE
[2.0 beta] Launch program minimized issue

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#51]
NOTE: This is a low-priority issue.

---

I've tried a few different programs with this and getting the same results.

Setup: Win7x86

Steps: 

1. Drag-and-drop a program to add (in this case OooPlayer 
2. Right click the newly added program and select Property

![2017-01-25 18_19_09-untitled - notepad](https://cloud.githubusercontent.com/assets/1289134/22315194/ee4ab58e-e32a-11e6-83be-511491fef471.png)

3. In the behavior tab, click "Minimize"

![2017-01-25 16_51_53-property](https://cloud.githubusercontent.com/assets/1289134/22312762/e6df4e60-e31e-11e6-8ce7-3f7ccb0b4bfb.png)

4. Click OK and launch program 

Defect: Program doesn't start minimized

**Comment by salvadorbs** [comment]
Unfortunately, ASuite uses api ShellExecute to run application or files. As you can see in https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea, this function can to set a flag for minimized or maximized, but it is application to decide how to handle it:

> The flags that specify how an application is to be displayed when it is opened. If lpFile specifies a document file, the flag is simply passed to the associated application. It is up to the application to decide how to handle it. These values are defined in Winuser.h.

So, we have two choices:

- Remove this option (er.. no )
- Get newly process of application started by asuite and set window as minimized or maximized. How? Use method CreateProcess only for .exe files (see https://stackoverflow.com/questions/8273588/delphi-shellexecute-and-sw-hide and https://www.delphipraxis.net/136375-shellexecute-windowhandle.html)

**Comment by salvadorbs** [comment]
Unfortunately given the past with issue #134, I would say that this issue cannot be fixed. Therefore I will close the ticket as "won't do / fix".
