### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#52]
Is this project still active or on hold?

**Comment by tunguyen6** [comment]
This is the best and most potential app launcher software out there. Especially it's free and open-source. As an user I'd love to support the development of this program, maybe through donation and feedback.

**Comment by vatterspun** [comment]
Hey if we could get someone to take over the project, that would be great.  I'd definitely throw in on that.

**Comment by salvadorbs** [comment]
Ehm... this project isn't dead, but... it isn't alive. I don't know what to call it. But you doesn't must expect great news or releases in the near future.

**Comment by vatterspun** [comment]
Woo hoo!  New release!  Closing case :)
