### ISSUE TITLE
Bug: Folder move makes icons disappear

### ISSUE THREAD

**Issue by vatterspun** [salvadorbs/Asuite#55]
Setup: Win7x86

Steps:

1. Download program and drag-and-drop some items
2. Move folder to another location on computer

Defect: no icons for programs

![ASuite_vyTptpdVs2](https://user-images.githubusercontent.com/1289134/81461430-b57a8f80-9179-11ea-8a41-151a6c4dff1a.png)

---

Workaround: open the program, right-click and select property, paste in the executable string to custom icon path:

![ASuite_4m2tOUDx37](https://user-images.githubusercontent.com/1289134/81461446-de028980-9179-11ea-8391-bc6cbdac88e6.png)

---

As a side note, I'm super happy to see this back in development.  Thanks very much for your work on this.  Definitely a big gap in portable tools to not have a flexible launcher working well on Win10.

**Comment by salvadorbs** [comment]
In these days, I have same bug when new version of a visual component (for ScanFolder, shell treeview) inadvertently call to rebuild system icon list. ASuite uses system imagelist and every icon has an index number, so software can retrieve icon using this number. With cache rebuilt, we have new index number, but ASuite uses old index yet. 

I resolved this, disabling this property of the visual component, but it seems it's not enough. 

Using your instructions, Windows 10 can't rebuild icon cache. But I will try to reproduce this bug in other ways (see https://www.howtogeek.com/232779/how-to-rebuild-a-broken-icon-cache-in-windows-10/). Thank you very much!

**Comment by teamayu** [comment]
The first time I ran the new version and selected to export the settings, all of the icons disappeared then as well.

**Comment by megabugman** [comment]
1. add a folder
2. move the folder
3. run, contradictory messagebox pops up
![move_folder](https://user-images.githubusercontent.com/17204819/126720538-3656b42c-868f-44db-86e7-7ad7e923a6cb.gif)

**Comment by salvadorbs** [comment]
it doesn't work as I hoped. I entered some default error messages. Thanks! 😄
