### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by teamayu** [salvadorbs/Asuite#56]
ASuite was working ok. I restarted the computer, now when I click on aSuite from the system tray to view the classic menu I see this:

![13-05-2020_135602](https://user-images.githubusercontent.com/10624092/81776592-ab61e380-9521-11ea-941a-de96f73b7918.png)

**Comment by salvadorbs** [comment]
Can you post here asuite.log? Thanks.

**Comment by teamayu** [comment]
No problem Salvador, here you go.

[ASuite.log](https://github.com/salvadorbs/Asuite/files/4620511/ASuite.log)

**Comment by salvadorbs** [comment]
I build another ASuite.exe (64bit) with some debug info. Can you try it and send me asuite.log again? Thank you very much.

[ASuite.zip](https://github.com/salvadorbs/Asuite/files/4626486/ASuite.zip)

**Comment by teamayu** [comment]
I have replaced the file and now the access violation doesn't appear.

[ASuite.log](https://github.com/salvadorbs/Asuite/files/4628129/ASuite.log)

**Comment by salvadorbs** [comment]
Very strange. I didn't change anything as well as add debug info. I will close this issue, but feel free to reopen this, if you have another AccessViolation. Thank you very much!

**Comment by teamayu** [comment]
It's happening again. It has been working fine, but now I get the access violation all the time. Clearly, something isn't quite right. :)

Log enclosed.

[asuite.log](https://github.com/salvadorbs/Asuite/files/4665732/asuite.log)

**Comment by teamayu** [comment]
I did close and restart the software, but still the same. The log has more info now though, which I have enclosed.

[ASuite.log](https://github.com/salvadorbs/Asuite/files/4665751/ASuite.log)

**Comment by salvadorbs** [comment]
Very strange. Thanks to your log, I found another access violation, but I didn't find your specific av. And I couldn't replicate it on my computer.

Anyway I build another asuite with a possible fix to your issue. Want to give it a try and tell me if it resolve this bug? Thank you so much!

[ASuite.zip](https://github.com/salvadorbs/Asuite/files/4669177/ASuite.zip)

**Comment by teamayu** [comment]
I have replaced the file and it is ok so far. Thank you. I'll let you know if anything happens.
