### ISSUE TITLE
'Run' in a Category (folder) not triggering anything

### ISSUE THREAD

**Issue by horacioj** [salvadorbs/Asuite#62]
Hi,
Run (F9 or Right-Click -> Run) in a Category (folder) isn't running any item (software) in the category.
It looks like a bug.
In case it isn't a bug, it could be a nice enhancement.  Or, the option to run a category should be removed.
Thanks

**Comment by salvadorbs** [comment]
Do you checked the category's items? For example:
![immagine](https://user-images.githubusercontent.com/3731721/90337214-5aaacc80-dfe1-11ea-8c44-f15694cb4bb3.png)

**Comment by horacioj** [comment]
Ah, that was it. Thanks!
