### ISSUE TITLE
Add Support for Environment Variables

### ISSUE THREAD

**Issue by Stephen-Leibowitz** [salvadorbs/Asuite#63]
PStart allows the user to set environment variables for each list item:

![PStartEnvVar](https://user-images.githubusercontent.com/11428233/91358948-b33c4f80-e7c1-11ea-8de3-01607bcf8232.PNG)

ASuite does not have the feature, and I suggest that it be considered for a future version of the launcher.

When importing from PStart, ASuite does not carry over the environment variables. The alternative for ASuite is to write a batch file for each list item that needs to set environment variables. Each batch file would set the variables and start the related program. The batch files would be invoked from ASuite.

**Comment by salvadorbs** [comment]
But these env variables are global (for every apps/software in windows) or associated with only the pstart item?

**Comment by Stephen-Leibowitz** [comment]
The short answer is “associated with only the PStart item.”

In PStart, Setup > Settings is for the global configuration of the launcher. It does not have the ability to set environment variables.

The ASuite main window screenshot shows the categories Audio, Internet, and Utility. The PStart equivalent is groups. One cannot set environment variables for PStart groups, only for individual files in a group, as explained in the next paragraph.

The ASuite screenshot shows individual items, including Coolplayer, XMPlay, Easy Message, I.Scribe, etc. They correspond to file items in PStart. For a file item in PStart, one can edit its **File properties**. The **Environment variables** tab in **File properties** allows you to set environment variables for that particular file item.

![ASuite_cr](https://user-images.githubusercontent.com/11428233/91556216-585d4200-e900-11ea-87b1-bc8b211629e7.png) ![start03](https://user-images.githubusercontent.com/11428233/91556237-627f4080-e900-11ea-9dd6-729cfdcfe8af.gif)

**Comment by muellerlukas** [comment]
I would love to have both.
Global Enviroment Variables (for e.g. JAVA_PATH/JAVA_HOME to a portable OpenJDK) and per-item variables for e.g. changing "%TMP%" to a per-software temp directory on a usb-stick.

**Comment by salvadorbs** [comment]
So you mean something like this https://www.nirsoft.net/articles/run-program-custom-environment-variables.html?

**Comment by Stephen-Leibowitz** [comment]
Yes. [SyMenu](https://www.ugmfree.it/SyMenuManual.aspx#SyProgramAdvancedEnvironmentVariables) also supports environment variables for individual items, such as PosteRazor.
