### ISSUE TITLE
Graphical Menu does not render on 150% display scaling?

### ISSUE THREAD

**Issue by joewez** [salvadorbs/Asuite#67]
I have a small UMPC with a 1920x1200 pixel touchscreen display, and am having an issue displaying the graphical menu.  When I click the Asuite icon, nothing appears to happen.  The classic menu seems to work although has a glitch when it first appears.... (it immediately disappears and I have to click again to have it work).  I believe it is resolution related, because when I change my display to an external 1080p monitor it works correctly.  Same software, same configuration... just a different display.

I am running an up-to-date version of Windows 10.

Thanks.

**Comment by joewez** [comment]
I found that it actually turns out to be the Scaling setting under Window's Display Settings.  At 150% scale the graphical menu fails to load.  At 125% it works.  Just an FYI.

**Comment by salvadorbs** [comment]
Tried. It works. If you want try too, you can download development build https://github.com/salvadorbs/Asuite/suites/1904816078/artifacts/37378842 . Attention: this version is highly unstable, and I do not recommend using it everyday.
