### ISSUE TITLE
Expand options window and variable drive letter

### ISSUE THREAD

**Issue by niccolleen** [salvadorbs/Asuite#68]
![Asuite](https://user-images.githubusercontent.com/53394948/93588009-0f525800-f9ab-11ea-844f-9a871319fd78.png)

Hi,
1. how do I set the dimensions of the options window right? I can't do it with the mouse. I can't get to the path button for example.

2. I successfully imported the backup file from my previous version. Those with $ drive letter don't work any more. How do I set a variable drive letter in the path? 

Thanks!
lg
niki

**Comment by vatterspun** [comment]
Here's what that same screen looks like on my machine (win10x64):

![image](https://user-images.githubusercontent.com/1289134/102174978-9f9a1f00-3e6c-11eb-84c4-d6ad7740c727.png)

Maybe this is a screen scaling issue?  I didn't used to have that problem.  What does your Settings - Display - Scaling and Layout screen look like?

**Comment by niccolleen** [comment]
Hello!

Thanks for your message.
I think, you are right. I’ve had the same problem with other programmes, too, in the meantime.
Thanks for this phantastic piece of software! Is it still maintained? It is the best, really.

best regards from Vienna,

niki

**Comment by salvadorbs** [comment]
Definitely it is a screen scaling issue. Meanwhile I changed development tools (from delphi to lazarus) and I will check it in next days. I have same issue when I run ASuite in Linux GTK (Ubuntu with Gnome Shell), so probably I need working on layout form.

**Comment by niccolleen** [comment]
Thanks for your reply and great to hear Asuite is still being looked after! :-)

**Comment by salvadorbs** [comment]
Fixed. Tried with 125%, 150% and 175%.

**Comment by niccolleen** [comment]
Great, tnx! Is there a new version available or just a confirmation, that it is a scaling issue?

**Comment by salvadorbs** [comment]
It is just a confirmation. If you want try it, download last build from Actions page (https://github.com/salvadorbs/Asuite/actions). 

P.S.: It is highly unstable build. Don't replace it with your ASuite 2.0. Better unzip it in another path and copy asuite.sqlite from 2.0 in it. So your list items is saved from "unforeseen consequences".

**Comment by niccolleen** [comment]
Thanks for the information!
I wouldn’t mind trying it out, but I’m no programmer and I could not find a link to a zip-file on that website you linked.
lg
Nicole

**Comment by salvadorbs** [comment]
Here's to you https://github.com/salvadorbs/Asuite/suites/1931593230/artifacts/38108456

**Comment by niccolleen** [comment]
That’s very kind of you, I get a 404 error though,
lg
Nicole

**Comment by salvadorbs** [comment]
Unluckily, you must login in github to download it. See https://github.com/actions/upload-artifact/issues/51 

Anyway, here to you. [ASuite Debug build - win32.zip](https://github.com/salvadorbs/Asuite/files/5902661/ASuite.Debug.build.-.win32.zip)

**Comment by oprypin** [comment]
(sorry for my drive-by comment, just pointing out a website I've made)

For links like https://github.com/salvadorbs/Asuite/suites/1931593230/artifacts/38108456
you can just substitute "https://github.com" with "https://nightly.link" and it will work without login.

**Comment by niccolleen** [comment]
Thank you!
Cool, it works!!
lg
niki
