### ISSUE TITLE
Add Information Text Field(s) to ASuite 2

### ISSUE THREAD

**Issue by Stephen-Leibowitz** [salvadorbs/Asuite#83]
In ASuite 1.5.2, Properties > Information
has these text fields: Description, Rating, and Notes.

![asuite_properties_info](https://user-images.githubusercontent.com/11428233/112975618-e06b2a80-9121-11eb-9e5a-e107bf6df39d.png)

The Property screen for a list item in ASuite 2 does not have an Information tab or any of its text fields.

In comparison, a Windows shortcut can store 259 characters in the Comment field. Also, each item in PStart has a Description field that serves as a comment. Edit > General > Description

**Comment by salvadorbs** [comment]
Yes, because ASuite 2 lost the card window (it has become useless over time). However, I could just re-add the Description field and display it as a tooltip when hovering over the item.

**Comment by Stephen-Leibowitz** [comment]
It is a good solution. The tooltip/popup on hover is the way Windows shortcuts work.
