### ISSUE TITLE
Option to disable the "Exit" and "Safely Remove Hardware" buttons in classic menu

### ISSUE THREAD

**Issue by actually-reb** [salvadorbs/Asuite#84]
Since I use ASuite as my main program launcher, the only thing these buttons do is accidentally close the program.

**Comment by salvadorbs** [comment]
Hi,

come to think of it, I'd rather add a confirmation message (with option to ask or not), instead of adding an option to disable the two items. What do you say?

**Comment by actually-reb** [comment]
If that's easier, sure! I've just gone exe hunting one too many times and was annoyed by it. Thank you for the response!
