### ISSUE TITLE
Heap dump by heaptrc unit

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#91]
Hi get an error message when running a1:

Heap dump by heaptrc unit of C:\Users\UserName\Downloads\ASuite21a_win32\ASuite.exe
3386 memory blocks allocated : 464346/472400
3386 memory blocks freed     : 464346/472400
0 unfreed memory blocks : 0
True heap size : 229376 (160 used in System startup)
True free heap : 229216

**Comment by salvadorbs** [comment]
Maybe memory leaks. (if it is a message box, click on OK button). You must wait 1-2 minutes and check the heap.trc. Thanks

**Comment by megabugman** [comment]
it is a message box
![image](https://user-images.githubusercontent.com/17204819/126084217-5759e2d8-73cb-49a1-be41-c826d96d32a3.png)
pops up sporadically after start

heap.trc, contains only
D:\ASuite21a\ASuite.exe 

for me the issue is reproducible by starting several instances:
![heap_dump2](https://user-images.githubusercontent.com/17204819/126084372-d38b5e5a-337a-4e5d-8b51-5620dc274cbb.gif)

**Comment by salvadorbs** [comment]
Forgot to ALWAYS set the globalSkipIfNoLeaks variable to true. So that no window is displayed in case there is no memory leak (as in the case when you start a second instance of asuite). Fixed.
