### ISSUE TITLE
error when saving empty list

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#92]
when saving an empty list, a message box pops up "Save completed".
and a garbage file is created
ã©ƒå•œæ•³ç²æ‘œæ¹¡æ•´ä‘œç¯æ±®æ…¯ç¤ä…œç•“ç‘©ã‰¥æ„±çŸæ¹©ãˆ³æ‰œæ¡ç•«å±°åæ¥µæ•´ã‰Ÿãˆ°â´±ãœ°ã„­â´¸ã„±ãˆ­â´¹ã˜±çŒ®æ‰±æ­£î¼€ê¶¾î¿žê¶¾ä‡žäˆŽÌ€Ð€è…+

**Comment by salvadorbs** [comment]
Can you run & exit asuite and send me the log file?

**Comment by megabugman** [comment]
please find attached the file
[file.zip](https://github.com/salvadorbs/Asuite/files/6837008/file.zip)

**Comment by salvadorbs** [comment]
Fixed.
