### ISSUE TITLE
heap.trc crash, don't know how to reproduce

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#96]
C:\Users\username\Downloads\ASuite21a_win32\ASuite.exe 
Heap dump by heaptrc unit of C:\Users\username\Downloads\ASuite21a_win32\ASuite.exe
1042063 memory blocks allocated : 586552823/587454384
1042061 memory blocks freed     : 586552703/587454264
2 unfreed memory blocks : 120
True heap size : 917504 (160 used in System startup)
True free heap : 916608
Should be : 916840
Call trace for block $0000000001623380 size 48
  $0000000100012CEB
  $000000010000F2F0
  $000000010039C606  ENUMERATEFORMATS,  line 4543 of VirtualTrees.pas
  $00000001003C4EA7  GETNATIVECLIPBOARDFORMATS,  line 22166 of VirtualTrees.pas
  $000000010039FA6B  CREATE,  line 99 of include/intf/win32/vtvdragmanager.inc
  $00000001003CFB05  CUTTOCLIPBOARD,  line 26659 of VirtualTrees.pas
  $00000001001371E0  ACTCUTEXECUTE,  line 208 of Forms/Forms.Main.pas
  $0000000100148A5C
  $000000010018ED44  EXECUTE,  line 98 of include/containedaction.inc
  $0000000100190BCC  EXECUTE,  line 246 of include/customaction.inc
  $00000001001487FB
  $0000000100189D6D  CLICK,  line 86 of include/menuitem.inc
  $000000010018A5AA  DOCLICKED,  line 293 of include/menuitem.inc
  $000000010000FEC1
  $0000000100258484  DOWINDOWPROC,  line 2058 of win32/win32callback.inc
  $0000000100259E47  WINDOWPROC,  line 2676 of win32/win32callback.inc
Call trace for block $0000000007F45D70 size 72
  $0000000100012C12
  $000000010000FABA
  $000000010001074A
  $000000010039FA0E  CREATE,  line 94 of include/intf/win32/vtvdragmanager.inc
  $00000001003CFB05  CUTTOCLIPBOARD,  line 26659 of VirtualTrees.pas
  $00000001001371E0  ACTCUTEXECUTE,  line 208 of Forms/Forms.Main.pas
  $0000000100148A5C
  $000000010018ED44  EXECUTE,  line 98 of include/containedaction.inc
  $0000000100190BCC  EXECUTE,  line 246 of include/customaction.inc
  $00000001001487FB
  $0000000100189D6D  CLICK,  line 86 of include/menuitem.inc
  $000000010018A5AA  DOCLICKED,  line 293 of include/menuitem.inc
  $000000010000FEC1
  $0000000100258484  DOWINDOWPROC,  line 2058 of win32/win32callback.inc
  $0000000100259E47  WINDOWPROC,  line 2676 of win32/win32callback.inc
  $00007FFF6A63E858

maybe this is also useful:

20210718 23355841 info  Execute Autorun List (Startup)
20210718 23355841 info  Refresh List
20210718 23355841  +    Database.Manager.TDBManager(062c49c0).SaveData
20210718 23355841  -    00.000.000
20210718 23355841 info  Saving ASuite SQLite Database
20210718 23355841 cache SynSQLite3.TSQLDatabase(01689d60) asuite.sqlite cache flushed
20210718 23355841 SQL   SynSQLite3.TSQLDatabase(01689d60) 19us asuite.sqlite BEGIN TRANSACTION;
20210718 23355841 info  Saving ASuite List
20210718 23355841 info  Saving ASuite Version
20210718 23355841 SQL   mORMotSQLite3.TSQLRestServerDB(063bcb90) 120us returned 1 row as 57 B SELECT ID,Major,Minor,Revision,Build FROM tbl_version
20210718 23355841 res   SynSQLite3.TSQLDatabase(01689d60) [{"ID":1,"Major":2,"Minor":1,"Revision":0,"Build":1264}] 
20210718 23355842 cache SynSQLite3.TSQLDatabase(01689d60) asuite.sqlite cache flushed
20210718 23355842 DB    mORMotSQLite3.TSQLRestServerDB(063bcb90) prepared 33us asuite.sqlite UPDATE tbl_version SET Major=?,Minor=?,Revision=?,Build=? WHERE RowID=?
20210718 23355842 SQL   mORMotSQLite3.TSQLRestServerDB(063bcb90) 15us  UPDATE tbl_version SET Major=:(2):,Minor=:(1):,Revision=:(0):,Build=:(1264): WHERE RowID=:(1):
20210718 23355842 SQL   SynSQLite3.TSQLDatabase(01689d60) 9us asuite.sqlite COMMIT TRANSACTION;
20210718 23355842 info  Start thread to get all icons
20210718 23355842  +    Icons.Thread.TTreeIconsThread(0638a550).Execute
20210718 23355842  -    00.000.000
20210718 23355842  +    GraphicMenu.ThemeEngine.TThemeEngine(07e42020).LoadTheme
20210718 23355842  -    00.000.000
20210718 23355842 info  Found theme.ini - Loading it
20210718 23360407  +    DataModules.TrayMenu.TdmTrayMenu(062cc710).UpdateClassicMenu
20210718 23360407  -    00.000.000
20210718 23360407 EXCOS EExternalException (c0000094) [] at   $00000001001DCCDA  RAISEGDBEXCEPTION,  line 50 of laztracer.pas

**Comment by salvadorbs** [comment]
But before the crash, did you only cut and paste one or more elements of the list?

I found a memory leak of the component displaying the list, but I can't reproduce the crash.

**Comment by megabugman** [comment]
Unfortunately, I don't know exactly how I managed to run into this issue.
I'll keep you informed once I know more.
Please feel free to close this issue unresolved in case you don't hear from me in within a month.

**Comment by megabugman** [comment]
can't provide any reproduction steps (yet)
![image](https://user-images.githubusercontent.com/17204819/126404522-b423bb82-be84-4d92-8069-83a37846575d.png)

**Comment by salvadorbs** [comment]
From what I see, the crash seems connected with this issue #104 and the memory leak does not seem to be the cause.

For the memory leak, you will probably need to clean the clipboard (if inside, the data is asuite) when the software is closed.

**Comment by megabugman** [comment]
#104 is most likely fixed, or I cannot reproduce the crash, hence I close this until I can provide steps to reproduce.
