### ISSUE TITLE
v2.1a TButtonedEdit active cursor missing in Search tab

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#97]
this works in v2.0
![expected](https://user-images.githubusercontent.com/17204819/126180289-d4bf10a7-e54e-4ba7-8fde-d3a20b23b09f.gif)

**Comment by salvadorbs** [comment]
Do you mean the focus on searchEdit (to save a click)?

**Comment by megabugman** [comment]
Firstly, thank you for your reply and for fixing already some of the reported bugs.
OK, I see you use different controls in V2.0 compared to V.2.1.

My expectation after pressing the Search Tab would be that the Edit Control gets activated and displays the cursor:
![image](https://user-images.githubusercontent.com/17204819/126367425-3b907af7-5e87-4783-bf79-801c2bdbd8d6.png)
-> like this I could immediately type/filter for applications.

Also I'd expect to see the caret when returning to the Search tab after clicking the List tab.
I hope this helps to understand the issue I see in here.

**Comment by salvadorbs** [comment]
>  OK, I see you use different controls in V2.0 compared to V.2.1.
Yes, it's basically a new component that I had to develop from scratch, as there is no component in Lazarus similar to the one in Delphi.

Now I should have restored the behavior as in asuite 2.0.

**Comment by megabugman** [comment]
nice, now go and prettify it :)

the cursor is almost not visible, consider changing the width and add some space between cursor and name like so
| name
![image](https://user-images.githubusercontent.com/17204819/126560078-21cb3dd6-ae5a-4d2f-a6e3-2e816ffa75e3.png)

**Comment by salvadorbs** [comment]
Unfortunately, this is the standard behavior of the editbox and cannot be changed to add a space between cursor and texthint.
