### ISSUE TITLE
About Window not modal

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#99]
from what I know, the about box should be modal like e.g in notepad or been closed when clicking in the main window like in Win10 calculator, though the latter is a UWP app. Keeping the about window open make no sense, IMO.
![not_modal](https://user-images.githubusercontent.com/17204819/126403760-bf8d6bdb-96a9-42f0-bb9d-838ad8cd842e.gif)

**Comment by salvadorbs** [comment]
In fact, it is much better to have the about window in modal mode. Thank you very much!
